### ISSUE TITLE
sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by joaochris** [Caltor/JWMediaCopier#2]
I followed all the steps, when I execute the command it gives this error.

**Comment by Caltor** [comment]
@joaochris Sorry about the delay on this. Today is my first day back in work since the holidays. Could you post the full error message please including the line number where the error occurs. The script accesses several database files so hopefully the full stack trace will tell me which one it is unable to open. Silly question but could you also just confirm that you have JW Library installed please and downloaded the current meeting workbook and Watchtower.

**Comment by joaochris** [comment]
@Caltor All fine brother! Does this script work in any language of the JW Library? Or was it set to English only? I was thinking about it just now. Because I am from Brazil.

**Comment by Caltor** [comment]
@joaochris Good question! I haven't checked it for internationalisation but it should work in theory if you change the language suffix at the end of line 3. In the UK our publications end with _E so could you change that to match your publications please. If that works let me know and I will update the documentation accordingly.

**Comment by joaochris** [comment]
@Caltor We are progressing kkkk. He is no longer giving the error. I just changed the language as you told me. Now we have another problem. He's not copying anything lol.

https://imgur.com/a/vqVwI5U

**Comment by Caltor** [comment]
> @Caltor We are progressing kkkk. He is no longer giving the error. I just changed the language as you told me. Now we have another problem. He's not copying anything lol.
> 
> https://imgur.com/a/vqVwI5U

OK I will need to investigate the code. Are you using "_T" for your publication suffix?

**Comment by joaochris** [comment]
@Caltor Tudo bem! Sim estou usando _T.

**Comment by Caltor** [comment]
It looks like in English the dates are stored in the database as "Month xx-yy" whereas in Portuguese and probably lots of other languages the date is stored as "xx-yy Month" causing the parsing to fail. :( I'll see if I can figure out a generic way to handle it, as with the (ever-expanding list of) languages on JW Library, I don't fancy having a different approach per language.

**Comment by joaochris** [comment]
@Caltor Understood! Okay, thanks in advance!

**Comment by Caltor** [comment]
@joaochris I've updated the script to try and accommodate multi-languagtes. It should work for any languages that use a Romanised alphabet such as English, French, Portuguese etc. Please download the script again. Change line 3 to read:
`language_suffix = "_T"`

and try to run it again. Let me know how you get on.
